swagger: '2.0'
info:
  description: REST API for search and fetching quotes
  version: 1.0.0
  title: Quote Service Rest API
  contact:
    name: samair
    url: samir.xyz
    email: tsameerc@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /
tags:
  - name: quotes-controller
    description: Quotes Controller
  - name: quotes-controller-v-2
    description: Quotes Controller V 2
paths:
  '/quotes/{symbol}':
    get:
      tags:
        - quotes-controller
      summary: getQoutes
      operationId: getQoutesUsingGET
      produces:
        - '*/*'
      parameters:
        - name: symbol
          in: path
          description: symbol
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GlobalQuote'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/search/{searchKey}':
    get:
      tags:
        - quotes-controller
      summary: searchSymbols
      operationId: searchSymbolsUsingGET
      produces:
        - '*/*'
      parameters:
        - name: searchKey
          in: path
          description: searchKey
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v2/quotes:
    get:
      tags:
        - quotes-controller-v-2
      summary: Lists quote infromation for one or more stock symbols
      operationId: getQuotesUsingGET
      produces:
        - '*/*'
      parameters:
        - name: symbols
          in: query
          description: symbols
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/v2/quotes/{symbol}':
    get:
      tags:
        - quotes-controller-v-2
      summary: Lists quote infromation of a stock's symbol
      operationId: getQoutesUsingGET_1
      produces:
        - '*/*'
      parameters:
        - name: symbol
          in: path
          description: symbol
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TradierPojo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/v2/search/{searchKey}':
    get:
      tags:
        - quotes-controller-v-2
      summary: Lists symbols for a given search key
      operationId: searchSymbolsUsingGET_1
      produces:
        - '*/*'
      parameters:
        - name: searchKey
          in: path
          description: searchKey
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SymbolSearch'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v2/session/stream:
    post:
      tags:
        - quotes-controller-v-2
      summary: Generate a stream session ID
      operationId: generateSessionIdUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /v2/stream:
    post:
      tags:
        - quotes-controller-v-2
      summary: 'Create a Stream session using sessionID '
      operationId: createStreamSessionUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: sessionId
          in: query
          description: sessionId
          required: true
          type: string
        - name: symbols
          in: query
          description: symbols
          required: true
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  BestMatchSymbol:
    type: object
    properties:
      1. symbol:
        type: string
      2. name:
        type: string
      3. type:
        type: string
      4. region:
        type: string
      5. marketOpen:
        type: string
      6. marketClose:
        type: string
      7. timezone:
        type: string
      8. currency:
        type: string
      9. matchScore:
        type: string
    title: BestMatchSymbol
  GlobalQuote:
    type: object
    properties:
      01. symbol:
        type: string
      02. open:
        type: string
      03. high:
        type: string
      04. low:
        type: string
      05. price:
        type: string
      10. change percent:
        type: string
      error:
        type: boolean
      invalidSymbol:
        type: boolean
    title: GlobalQuote
  SearchResult:
    type: object
    properties:
      bestMatches:
        type: array
        items:
          $ref: '#/definitions/BestMatchSymbol'
    title: SearchResult
  SymbolSearch:
    type: object
    properties:
      securities:
        $ref: '#/definitions/SearchResult'
    title: SymbolSearch
  TradierPojo:
    type: object
    properties:
      quotes:
        $ref: '#/definitions/TradierQuotes'
    title: TradierPojo
  TradierQuotes:
    type: object
    properties:
      error:
        type: boolean
      invalidSymbol:
        type: boolean
    title: TradierQuotes
